networks:
  selenium-net:
    driver: bridge

services:
  selenium-hub:
    image: selenium/hub:4.31.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - selenium-net
  selenium-node-chrome:
    image: selenium/node-chrome:4.31.0
    container_name: selenium-node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-net
  selenium-node-firefox:
    image: selenium/node-firefox:4.31.0
    container_name: selenium-node-firefox
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-net
  car-checking-tests:
    build: .
    container_name: car-checking-tests
    depends_on:
      - selenium-hub
      - selenium-node-chrome
      - selenium-node-firefox
    environment:
      - HUB_HOST=selenium-hub
      - USE_REMOTE_DRIVER=true
    networks:
      - selenium-net
    volumes:
      - ./src/test/resources:/app/src/test/resources  # Mounting the resources directory